FROM osixia/openldap:1.5.0
MAINTAINER Oleksandr "Alex" Kuznetsov alex.kuznetsov@osi.ca.gov

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom
